rules = [
  DisableSyntax,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  ProcedureSyntax
]

DisableSyntax {
  noVars = false
  noThrows = false
  noNulls = false
  noReturns = false
  noWhileLoops = false
  noAsInstanceOf = false
  noIsInstanceOf = false
  noXml = false
  noDefaultArgs = false
  noFinalVal = false
  noFinalize = true
  noValPatterns = false
}
